language: "en"

pipeline:
#- name: "nlp_spacy"
#- name: "tokenizer_spacy"
- name: "tokenizer_whitespace"
#- name: "ner_synonyms"
- name: "bert_vectors_featurizer"
- name: "intent_classifier_tensorflow_embedding"
- name: "ner_crf"
  intent_tokenization_flag: true
  intent_split_symbol: "."
  "epochs": 200
  "droprate": 0.5