language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
#- name: "composite_entity_extractor"
- name: "tokenizer_whitespace"
- name: "intent_featurizer_count_vectors"
- name: "universal_sentence_encoder_featurizer"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "."
  "epochs": 200
  "droprate": 0.5
